name: UhcEspectralClases
version: '${project.version}'
main: online.espectral.uhcespectralclases.UhcEspectralClases
api-version: '1.20'
commands:
  class:
    description: "Main Command for UHC ESPECTRAL CLASES"